export const FETCH_HIGHSCORES_PENDING = "FETCH_HIGHSCORES_PENDING";
export const FETCH_HIGHSCORES_SUCCESS = "FETCH_HIGHSCORES_SUCCESS";
export const FETCH_HIGHSCORES_ERROR = "FETCH_HIGHSCORES_ERROR";
export const FETCH_HIGHSCORES_REQUEST = "FETCH_HIGHSCORES_REQUEST";
