import {
    FETCH_COMMENTS_PENDING,
    FETCH_COMMENTS_SUCCESS,
    FETCH_COMMENTS_ERROR,
    FETCH_COMMENTS_REQUEST
} from './comments';

import {
    FETCH_HIGHSCORES_PENDING,
    FETCH_HIGHSCORES_SUCCESS,
    FETCH_HIGHSCORES_ERROR,
    FETCH_HIGHSCORES_REQUEST
} from './highscores';

import { CHANGE_SLIDE } from './previewSlider';

import { CHANGE_BANNER_SLIDE } from'./sliderBanner';

import {
    LOGIN,
    LOGOUT,
    BUY
} from './user';

export {
    FETCH_COMMENTS_PENDING,
    FETCH_COMMENTS_SUCCESS,
    FETCH_COMMENTS_ERROR,
    FETCH_COMMENTS_REQUEST,
    FETCH_HIGHSCORES_PENDING,
    FETCH_HIGHSCORES_SUCCESS,
    FETCH_HIGHSCORES_ERROR,
    FETCH_HIGHSCORES_REQUEST,
    CHANGE_SLIDE,
    CHANGE_BANNER_SLIDE,
    LOGIN,
    LOGOUT,
    BUY
};
